### ISSUE TITLE
[Feat] Allow external secret for secretFiles

### ISSUE THREAD

**Issue by rchincha** [project-zot/helm-charts#10]
https://github.com/project-zot/zot/discussions/1721

**Comment by loicalbertin** [comment]
### Discussed in https://github.com/project-zot/zot/discussions/1721

<div type='discussions-op-text'>

<sup>Originally posted by **loicalbertin** August 22, 2023</sup>
Hi :wave:

Context: I want to deploy Zot using a GitOps tool (I'm using Rancher Fleet).

Issue: The Helm config will be stored into Git. With the current Zot Helm chart I should store the `secretFiles` unencrypted into my git repo. This is problematic to me.

Having secrets into Git repo is a well-known issue when dealing with GitOps. 
Personally I use Sops + a Kubernetes Operator to deal with it and store my secrets encrypted in the Git repo. 

So I will be able to pre-generate a secret similar to the one generated by the Helm chart using the value of `secretFiles` prior to the chart deployment.

What is missing for me in the Zot Helm is either:
- a way to specify the name of a secret to be mounted in the container in place of the secret generated by the chart 
- or just not generating the secret for `secretFiles` if a secret of the same name already exits (I will manage to create a secret with the correct name)

What do you think about this?</div>

**Comment by rchincha** [comment]
@loicalbertin do you want to give us a PR for this? We can review and work off of that.

**Comment by loicalbertin** [comment]
Opened a PR to start discussion.
I retained the first proposed solution (allow to specify another secret name).
