### ISSUE TITLE
[Feat]: Add configurable startupProbe

### ISSUE THREAD

**Issue by Kortekaasy** [project-zot/helm-charts#34]
Currently, the deployment uses the livenessProbe to check whether the Zot pods are ready to start receiving requests. When using the new search extension from Zot 2.0.0 in combination with remote storage, it can take a while for the Zot pods to become ready. If this takes too long, Kubernetes will kill the pods off before giving them a fair chance to become healthy.

Therefore, I suggest we add a startupProbe to the deployment, which can be configured with e.g. a higher failure threshold. With a higher failure thresholds Pods in this scenario can get some extra time to become healthy.

**Comment by Jean-Daniel** [comment]
I actually encounter this issue, and my registry can't start as it is killed before it is ready.

> With a higher failure thresholds Pods in this scenario can get some extra time to become healthy.

Actually, you don't need a higher threshold, as Kubernetes does not start checking readiness/liveness until the startup probe is OK.

> The kubelet uses startup probes to know when a container application has started. If such a probe is configured, liveness and readiness probes do not start until it succeeds

**Comment by Kortekaasy** [comment]
You do seem to need the higher failure threshold for the startupProbe, the readiness/liveness probes can remain as they are.
