### ISSUE TITLE
Add support prometheus-operator?

### ISSUE THREAD

**Issue by batazor** [project-zot/helm-charts#41]
This will simplify the process of collecting Prometheus metrics

**Comment by rchincha** [comment]
@batazor would you like to submit a PR (draft even) to get this started?

**Comment by batazor** [comment]
@rchincha done

**Comment by rchincha** [comment]
@batazor 
Pls reopen your PR and fix as per https://github.com/project-zot/helm-charts/pull/42#issuecomment-2263681319

**Comment by batazor** [comment]
@rchincha I can't reopen the past PR, but I've created a new PR with the suggested fixes in mind https://github.com/project-zot/helm-charts/pull/45
