### ISSUE TITLE
Add a way to configure the namespace

### ISSUE THREAD

**Issue by rgl** [project-zot/helm-charts#46]
I'm trying to install Zot using `helm template` (actually using the [`helm_template` terraform data source](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/data-sources/template)) into Talos Kubernetes, but without a way (e.g. a `namespace` helm value) to set the namespace, Zot can only be installed at the `default` namespace, which is a bummer.

A possible way is suggested at https://gitea.com/gitea/helm-chart/issues/630.

**Comment by rchincha** [comment]
@rgl 

Do you want to open/attempt a PR for this?
https://github.com/project-zot/helm-charts/commit/acb80f182d74c20c4d5a2d580909eafc758ca457

**Comment by rchincha** [comment]
https://github.com/project-zot/helm-charts/pull/49
^ should address this issue.
Closing.
