### ISSUE TITLE
Prevent releases of this chart with pre-releases of zot

### ISSUE THREAD

**Issue by rgl** [project-zot/helm-charts#47]
Somehow, please prevent making releases of this chart with pre-releases of zot.

For example, https://github.com/project-zot/helm-charts/releases/tag/zot-0.1.61 [was released with zot v2.1.2-rc1](https://github.com/project-zot/helm-charts/blob/zot-0.1.61/charts/zot/values.yaml#L9).

**Comment by rchincha** [comment]
@rgl 

Noted. For now, folks have to pay attention to the "default" image version being shipped with a helm chart.

**Comment by andaaron** [comment]
Fixed in #2755
